services:
  db:
    image: mysql
    volumes:
      - "./docker/.data/db:/var/lib/mysql"
      # - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - "./docker/db/sql:/docker-entrypoint-initdb.d"

    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"
